### ISSUE TITLE
Problem with `show-paren-style`

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/zerodark-theme#1]
When setting `show-paren-style` to `expression` or `mixed`, the highlighted region is really ugly. The `show-paren-match` face needs tweaking in zerodark.

**Comment by NicolasPetton** [comment]
It's hard to have a color that works well in both modes. Would you have a suggestion?

**Comment by DamienCassou** [comment]
Nicolas Petton notifications@github.com writes:

> It's hard to have a color that works well in both modes. Would you
> have a suggestion?

which modes?

## 

Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by NicolasPetton** [comment]
I meant in both cases.

**Comment by NicolasPetton** [comment]
I experimented a bit, and it's really hard to find a color that works in both cases.  I tried with other themes as well, and even wiht solarized it looks ugly when retting `show-paren-style` to `expression`.

I have no plan to fix this issue, so I'm closing it.
