### ISSUE TITLE
New modeline

### ISSUE THREAD

**Issue by manuel-uberti** [NicolasPetton/zerodark-theme#14]
Although the new modeline is fantastic, it requires the icons from `all-the-icons` installed to work, am I right?

Maybe it should be made optional, or there should be something that suggests to user to configure the icons.

Just a thought :)

**Comment by NicolasPetton** [comment]
> Maybe it should be made optional, or there should be something that
> suggests to user to configure the icons.

The package `all-the-icons` should be installed as a dependency when you
install zerodark.  Isn't it the case?

**Comment by manuel-uberti** [comment]
Yes, but the icons must be installed in order to appear in the command line. 

In my case, I just put them in `~/.fonts` and ran `fc-cache -fv`. After that, they were correctly displayed in the modeline.

From `all-the-icons` [README](https://github.com/domtronn/all-the-icons.el):

> However, in order for the icons to work you will need to install the Resource Fonts included in this package, they are available in the fonts directory.

**Comment by NicolasPetton** [comment]
Manuel Uberti notifications@github.com writes:

> Yes, but the icons must be _installed_ in order to appear in the command line. 
> 
> In my case, I just put them in `~/.fonts` and ran `fc-cache
> -fv`. After that, they were correctly displayed in the modeline.

Hmm, weird, I didn't have to do anything.

Nico

**Comment by NicolasPetton** [comment]
Manuel Uberti notifications@github.com writes:

> Yes, but the icons must be _installed_ in order to appear in the
> command line.

Ok, I see now, the fonts were already installed on my system.
Do you want to update the README?

**Comment by manuel-uberti** [comment]
Sure, I'll do it and open a PR. :)
