### ISSUE TITLE
Additional fonts and new modeline

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/zerodark-theme#16]
Thanks for updating the README. Nevertheless, I think it's problematic to activate the new modeline by default and require additional work from the users. The new modeline will break user configurations of all users who don't have fontawesome installed.

**Comment by NicolasPetton** [comment]
> Thanks for updating the README. Nevertheless, I think it's problematic
> to activate the new modeline by default and require additional work
> from the users. The new modeline will break user configurations of all
> users who don't have fontawesome installed.

Indeed, I will make it opt-in.

Nico

**Comment by NicolasPetton** [comment]
Fixed in commit 809379d
