### ISSUE TITLE
anzu's modeline additions are not visible with new modeline

### ISSUE THREAD

**Issue by DamienCassou** [NicolasPetton/zerodark-theme#19]
Press `C-s` and search for something in the current buffer. `anzu` displays the number of matches in the modeline, but this is unreadable in zerodark with the alternate modeline.

**Comment by NicolasPetton** [comment]
Is it? That's what I get:

![screenshot from 2016-10-08 12-03-16](https://cloud.githubusercontent.com/assets/123539/19212339/4070346a-8d4f-11e6-96ad-b2687272ac4f.png)

**Comment by DamienCassou** [comment]
Sorry, problem of my own configuration.
