### ISSUE TITLE
Drop s.el dependency?

### ISSUE THREAD

**Issue by fice-t** [NicolasPetton/zerodark-theme#22]
It seems that you only use `s-truncate` from `s.el`. Instead, would it be better to use the built-in `truncate-string-to-width` and drop the extra dependency?

PS: Is there a reason why `powerline` isn't an optional dependency just like `powerline-evil`?

**Comment by NicolasPetton** [comment]
Yes, `s.el` can be removed. For powerline, it's a bit different, as powerline functions are used for formatting the mode-line.

**Comment by fice-t** [comment]
@NicolasPetton Thanks. Did you want to keep the ellipsis at the end of the truncated strings? If so, then you would need to specify the last argument in `truncate-string-to-width`.

> For powerline, it's a bit different, as powerline functions are used for formatting the mode-line.

Oh I see, I was searching for `power` but some powerline functions start with `pl`.

I'm not sure whether `powerline` should be a mandatory dependency since the special mode-line is optional, but it makes more sense now.

**Comment by NicolasPetton** [comment]
@fice-t Thanks, I added back the ellipsis.
