### ISSUE TITLE
differentiate org-level-3 and org-level-4

### ISSUE THREAD

**Issue by ninrod** [NicolasPetton/zerodark-theme#28]
right now org-level-3 and org-level-4 have the same colouring. consider using a different color for each one in order to increase readability.

<img width="284" alt="screen shot 2016-11-23 at 23 52 26" src="https://cloud.githubusercontent.com/assets/8352747/20597651/117f4ac2-b22c-11e6-8e5c-2203395ede98.png">

**Comment by NicolasPetton** [comment]
@ninrod do you want to send a patch/open a PR?

**Comment by ninrod** [comment]
I'd love to @NicolasPetton, but I'm still beggining to learn elisp! And I trust that you have a way more refined taste for the zerdark color palete. 

What do you think would be a good color to cycle between org-level-3 and org-level-4?

**Comment by ninrod** [comment]
@NicolasPetton, so after your suggestion I've decided to take a shot at a pull-request for this, which turned out to be way easier then I anticipated. ref: #29
