### ISSUE TITLE
Cursor color is black

### ISSUE THREAD

**Issue by quimm2003** [NicolasPetton/zerodark-theme#3]
Hi, Nicolas, thank you for this nice theme.

I have an issue, my cursor color is black and there's no way to change it. Every time I start emacs, the cursor color is black over the default background, which makes it difficult to locate, sometimes.

I've reviewed carefully my code and deleted all custom color settings.

Is there a way to get the default foreground color, which is lighter, I presume?

Thanks,

Quim

Emacs version:
GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, X toolkit, Xaw3d scroll bars) of 2015-10-01

Linux:
Linux 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt4-3~bpo70+1 (2015-02-12) x86_64 GNU/Linux

**Comment by vyp** [comment]
Are you running emacs in the terminal, because I guess then it might be your terminal settings that are not allowing you to change the color? Because otherwise can't you just change the `cursor` face? I don't think it's a problem with the theme itself because it has this line: https://github.com/NicolasPetton/zerodark-theme/blob/4144e6ab2908a2db4448c0fbe1f9f143e2fc9818/zerodark-theme.el#L71

**Comment by quimm2003** [comment]
I'm aware of this line, I even tried to change it and byte-compile the theme, without success.

Currently I start emacs server as a daemon in gui mode, plus emacsclient, executing a script from the terminal: 

emacs --daemon=DEV >/dev/null 2>&1 &
emacsclient -c -s DEV -f emacsdev -q &

I call (load-theme 'zerodark t) at the end of my .emacs file, immediately before (provide 'emacs), trying to override any previous settings, without success.

As a workaround the cursor color looks fine when loading the theme manually once emacsclient has started.

**Comment by vyp** [comment]
Just a stab in the dark, I remember something about having problems with themes when starting as a daemon due to something about no frame being made... can you try the following (at the end of your .emacs):

``` elisp
(if (daemonp)
    (add-hook 'after-make-frame-functions
              (lambda (frame)
                (with-selected-frame frame
                  (load-theme 'zerodark t))))
  (load-theme 'zerodark t))
```

> As a workaround the cursor color looks fine when loading the theme manually once emacsclient has started.

This is why I'm guessing the above...

**Comment by quimm2003** [comment]
Your guess is right! That do the trick.

Thank you very much.

**Comment by vyp** [comment]
Awesome! :sparkles:

**Comment by quimm2003** [comment]
It may be useful if you put this code in the README as an advice...

**Comment by vyp** [comment]
I don't use melpa, I wonder if the problem still happens when doing:

```
M-x package-install RET zerodark-theme
```

instead?

Anyway, I'm not the author here, so I'll let @NicolasPetton decide if he wants to add that to the README. I agree though, it's probably useful to put there.

**Comment by quimm2003** [comment]
I've installed the theme via package-install and melpa, so I guess the
problem will still happen.

**Comment by vyp** [comment]
Ah thanks for trying that out, I wonder if it could solved directly in `zerodark-theme.el` somehow? Otherwise yes, I guess it should be put in the README then.

**Comment by quimm2003** [comment]
I'm sorry, I'm not an elisp expert, so I can't help with solving it in the theme
file.

**Comment by vyp** [comment]
That's okay, Nicolas will probably know the answer.

**Comment by NicolasPetton** [comment]
I am glad you're issue is solved.  I don't know if there is a way to fix the problem in the theme itself though.

**Comment by quimm2003** [comment]
It works like a charm, Nicolas, I'm very happy with it.

Thank you very much.

**Comment by hughlt** [comment]
Did not know about that hook!  I was getting a black cursor on new frames in tsdh-dark and other dark themes.   Fixed it with:
(add-hook 'after-make-frame-functions
      (lambda (frame)
        (with-selected-frame frame
          (set-cursor-color "cyan"))))
