### ISSUE TITLE
Multiple cursors don't show up

### ISSUE THREAD

**Issue by iAmMrinal0** [NicolasPetton/zerodark-theme#33]
Multiple cursors selection works and multiple regions are highlighted whereas adding new cursors don't show up. The cursors are there just not highlighted.

**Comment by manuel-uberti** [comment]
I get this:
![screenshot from 2017-04-08 14-31-06](https://cloud.githubusercontent.com/assets/8199224/24828914/0e757472-1c68-11e7-8976-6227ceccdce6.png)

Isn't it what you mean by highlighted?

**Comment by iAmMrinal0** [comment]
Multiple cursors works if you have a region selected, the matching regions are highlighted. But if you don't have a region selected and add multiple cursors(which adds a cursor to the next lines), currently only one cursor is shown even though the cursors are added. There is no visual indication of the new cursors even when multiple cursors indicates it has `x` number of cursors(indicates in the modeline).

Hope I have been clear.

**Comment by manuel-uberti** [comment]
The screenshot above didn't involve any region being selected.I get that by doing either `mc/mark-next-like-this` or by issuing `set-rectangular-region-anchor` on the first line and then doing <kbd>C-n</kbd> to get to next lines.

**Comment by iAmMrinal0** [comment]
![screenshot from 2017-04-08 21-15-45](https://cloud.githubusercontent.com/assets/890062/24830290/85650f2e-1ca0-11e7-9eca-498f1452bdb5.png)

This is an example in the `dracula` theme. I just go to point where I need cursors and without any selection do `mc/mark-next-like-this` and it adds cursors as I keep invoking the command. In `zerodark` though the cursors are added, only the first one is visible.

![screenshot from 2017-04-08 21-23-35](https://cloud.githubusercontent.com/assets/890062/24830330/98a03b94-1ca1-11e7-99e0-476bd3f0f5c1.png)

This is in `zerodark` where the cursors are added but they aren't visible. Their color is too dim and not visible at all.

**Comment by iAmMrinal0** [comment]
My mistake, sorry. It works properly.
I am not sure why this happens but I figured that `js2-refactor` caused this issue. I use `use-package` and when I `defer` `js2-refactor` the cursors show up but when I don't they don't show up. I currently don't have the knowledge to make sure that `js2-refactor` is causing this.

**Comment by NicolasPetton** [comment]
Could you open an issue in js2-refactor?
https://github.com/magnars/js2-refactor.el
