### ISSUE TITLE
Needs a GNU v3 compatible license.

### ISSUE THREAD

**Issue by milkypostman** [NicolasPetton/zerodark-theme#34]
creative commons is not a software license: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by NicolasPetton** [comment]
I thought about an Emacs theme as artwork, but indeed it seems to be wrong.

**Comment by milkypostman** [comment]
sorry, you have to update the individual files too. i hadn't figured out what to say, but here is more information.

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this permission statement to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.
```

Also consider adding a LICENSE file containing the text of the GPL-3. You could add just that file without also adding the above persmission statement, but if you do that, then the "or (at your option) any later version" bit won't be known. So I recommend that you add both the actual license and the permission statement.

If you find the permission statement to be too noisy, then you could instead add one of these following lines to the header. If you do that, then it becomes more important to also add the LICENSE file - a judge might decide that such a line by itself is not sufficient. Still, adding just such a line is better than not specifing the license at all.

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by NicolasPetton** [comment]
Sorry, I forgot the source files :/

**Comment by NicolasPetton** [comment]
@milkypostman done!

**Comment by NicolasPetton** [comment]
@milkypostman there's already a LICENSE file, or am I missing something?

**Comment by milkypostman** [comment]
More important is the license header at the top of the file. That's what
the problem was. The .el file still had Creative Commons listed as the
license.
