### ISSUE TITLE
Can't find the theme on melpa

### ISSUE THREAD

**Issue by hisnawi** [NicolasPetton/zerodark-theme#35]
Was this package pulled from melpa? Can't find it anymore.

**Comment by NicolasPetton** [comment]
It looks like it, because of a license issue (which has been fixed). I guess that the package should be added back soon.

/cc @milkypostman

**Comment by milkypostman** [comment]
If you send a PR to melpa I can commit now otherwise it'll be until this
evening before I can get to it.

Thanks and sorry for the inconvenience.

**Comment by hisnawi** [comment]
Thanks. I will wait, no rush.
