### ISSUE TITLE
Add support for ansi-term

### ISSUE THREAD

**Issue by manuel-uberti** [NicolasPetton/zerodark-theme#4]
Hi,

thanks for this great theme. Would it be possible to add support for ansi-term?
Currently it looks like this:
![2015-11-05-125849_1266x205_scrot](https://cloud.githubusercontent.com/assets/8199224/10967757/10636626-83bd-11e5-8cf8-c219f23f9518.png)
It could look like Eshell, which is actually pretty awesome:
![2015-11-05-130019_1204x169_scrot](https://cloud.githubusercontent.com/assets/8199224/10967777/33e9f786-83bd-11e5-8516-06dbf1fc29bb.png)

**Comment by NicolasPetton** [comment]
@manuel-uberti Can you confirm that it looks ok?

**Comment by manuel-uberti** [comment]
Yes, it's a real beauty! Thanks a lot
