### ISSUE TITLE
Distinguish the shadow face

### ISSUE THREAD

**Issue by justbur** [NicolasPetton/zerodark-theme#41]
When I use this theme, the setting for the `shadow` face seems to be the default and not really distinguishable from `default` text.

**Comment by NicolasPetton** [comment]
Justin Burkett <notifications@github.com> writes:

> When I use this theme, the setting for the `shadow` face seems to be
> the default and not really distinguishable from `default` text.

Hi Justin,

Do you have an example usage of the shadow face?

**Comment by justbur** [comment]
The only place I'm aware of is in evil-mode, which uses it to display the previously used ex command. Here's a screenshot

![screen shot 2018-01-25 at 8 13 19 am](https://user-images.githubusercontent.com/2208382/35390019-f598f6c4-01a7-11e8-96ac-f04640adf941.png)

The face is the same as `default` which is confusing in this context, because the command is not actually entered yet.

If I use leuven, for example, this face looks like a comment (grayed out), which makes sense if you are showing the previous command, but it is not yet entered into the minibuffer.

![screen shot 2018-01-25 at 8 18 10 am](https://user-images.githubusercontent.com/2208382/35390168-6e473b8a-01a8-11e8-89d9-9d7a2a2df050.png)

Hopefully that makes sense.

**Comment by NicolasPetton** [comment]
Master has a fix for it, I'm closing this issue.

If the face doesn't suit your needs, feel free to reopen this issue.

**Comment by justbur** [comment]
Thanks!
