### ISSUE TITLE
Do not override foreground color on selected region

### ISSUE THREAD

**Issue by pierrelegall** [NicolasPetton/zerodark-theme#49]
Foreground colors are overridden on region as you can see below.

![Example](https://media.giphy.com/media/1AP8EjSoyfc1a6HuVF/giphy.gif)

Maybe could we just keep the syntax highlighting on region too?

**Comment by NicolasPetton** [comment]
IIRC I experimented with both, and ended up with the current behavior.

I'll give it another try though :)

**Comment by NicolasPetton** [comment]
I removed the foreground override, so people can give it a try for some time.
