### ISSUE TITLE
Add support for elfeed

### ISSUE THREAD

**Issue by manuel-uberti** [NicolasPetton/zerodark-theme#5]
Currently it looks like this:
![2015-11-05-130226_1167x90_scrot](https://cloud.githubusercontent.com/assets/8199224/10967820/86bcad5a-83bd-11e5-9d4a-6badc4ccc974.png)
Would it be possible to add faces more similar to these?
![2015-11-05-130330_567x129_scrot](https://cloud.githubusercontent.com/assets/8199224/10967832/a85f08c2-83bd-11e5-9db7-2a785b936a97.png)

**Comment by manuel-uberti** [comment]
Any news on this one? :)

**Comment by NicolasPetton** [comment]
No, sorry.

Would you like to add it?

**Comment by manuel-uberti** [comment]
Sure, but it's going to take a while, only have time during the weekends now. If you're not in a hurry, I could give it a shot.
