### ISSUE TITLE
Diff-hl face and font size increased problem

### ISSUE THREAD

**Issue by pierrelegall** [NicolasPetton/zerodark-theme#50]
The current diff-hl face is:

![Current diff-hl face](https://i.imgur.com/KNoRdVz.png)

However, I prefer a more sober face:

![Proposal for diff-hl face](https://i.imgur.com/4Aj1YDC.png)

Moreover, it's a workaround to avoid the problem below when you increase the font size:

![Diff-hl font size increased problem](https://i.imgur.com/AVljDY3.png)

What do you think about this choice?

**Comment by NicolasPetton** [comment]
The background face alone makes it hard to distinguish between the red and purple on one line changes IMO.

**Comment by pierrelegall** [comment]
Blue is often used for modified lines. I will make a new proposal this evening.

**Comment by pierrelegall** [comment]
What do you think of this one?

![New proposal](https://i.imgur.com/WoZCaUO.png)

I re-used the current `bright-background-*` faces for this one. If it's too bright, maybe we should create new colors.

See #51 last change (I should not have posted an issue and a PR).
