### ISSUE TITLE
Why are there dependencies on Flycheck and Magit?

### ISSUE THREAD

**Issue by raxod502** [NicolasPetton/zerodark-theme#53]
On the face of it, there does not seem to be any reason for a color theme to declare hard dependencies on Flycheck and Magit, just because it provides face customizations for them. Can these dependencies be removed?

**Comment by NicolasPetton** [comment]
yes, they should be removed.

**Comment by raxod502** [comment]
I created a pull request for this.

**Comment by NicolasPetton** [comment]
Thanks, I'm closing this issue.
