### ISSUE TITLE
Completion buffer, parenthesis, function, type improvemenents

### ISSUE THREAD

**Issue by ChoppinBlockParty** [NicolasPetton/zerodark-theme#59]
Thank you for a great theme. Wanna give here a little feedback.

Here are the modifications that I added to my configuration.

``` elisp
    ;;; Improve type variable visibility (helpful in c-like language)
    '(font-lock-type-face          ((t (:foreground "#5fafaf"))))
    '(font-lock-variable-name-face ((t (:foreground "#d7875f"))))

    ;;; Improve parenthesis matching visibility
    '(show-paren-match             ((t (:background "#7f1de1" :foreground "#1f1623" :weight extra-bold))))
    ;;; Improve parenthesis matching visibility
    '(completions-annotations      ((t (:foreground "#ff6c6b"))))
    '(completions-common-part      ((t (:foreground "#4e5079"))))
    '(completions-first-difference ((t (:foreground "#da8548" :weight bold))))
```
![selection_021](https://user-images.githubusercontent.com/28957323/46151897-19379980-c270-11e8-92ae-2d8d908bc851.png)
![selection_020](https://user-images.githubusercontent.com/28957323/46151903-1d63b700-c270-11e8-8264-a098aa021dae.png)

**Comment by NicolasPetton** [comment]
Thanks! Nice customizations, some of it could go into zerodark. Would you mind making pull requests?
