### ISSUE TITLE
Add support for diff-hl

### ISSUE THREAD

**Issue by manuel-uberti** [NicolasPetton/zerodark-theme#6]
Currently `diff-hl` colors in the fringe are a bit hard to notice:
![2015-11-05-130650_767x628_scrot](https://cloud.githubusercontent.com/assets/8199224/10967902/2d3d91da-83be-11e5-820f-7d0f0160575a.png)

**Comment by manuel-uberti** [comment]
Any news on this one? :-)

**Comment by NicolasPetton** [comment]
should be better now!

**Comment by manuel-uberti** [comment]
Thank you!
