### ISSUE TITLE
it is broken if you don't have flycheck installed

### ISSUE THREAD

**Issue by a-schaefers** [NicolasPetton/zerodark-theme#61]
Without flycheck it will just spam your screen with error messages about how it needs flycheck

**Comment by a-schaefers** [comment]
Actually even with flycheck installed, it still is broken. It requires loading :after flycheck and then it will work as expected.

Nice looking theme, by the way :)

**Comment by NicolasPetton** [comment]
Thanks! I use zerodark daily (with flycheck installed), and I don't have any error message.
Can you tell me how do you load/enable zerodark?

**Comment by NicolasPetton** [comment]
Can you try with https://github.com/NicolasPetton/zerodark-theme/commit/ef5bdb215ad7ed9e11ae0550105775794277bf65 and see if it fixes the issue for you?

**Comment by a-schaefers** [comment]
Sure, here is my init https://github.com/a-schaefers/dot-emacs/blob/master/init.el

and I load the theme inside https://github.com/a-schaefers/dot-emacs/blob/master/lisp/cfg-appearance.el

with this bit:

```
(use-package zerodark-theme
  :init (use-package all-the-icons :config
          (unless (file-exists-p "~/.local/share/fonts/all-the-icons.ttf")
            (all-the-icons-install-fonts t)))
  :after flycheck
  :config
  (load-theme 'zerodark t)
  (zerodark-setup-modeline-format)
  (set-cursor-color "#000000"))
```

It didn't work as expected without ":after flycheck"

I will test your update right now and let you know.

**Comment by a-schaefers** [comment]
Hey thanks for fixing it, I can report it is good now.

**Comment by CDitzel** [comment]
I stll have this issue that flycheck is required. Why is that and how can I change it?
