### ISSUE TITLE
Icon problem modeline

### ISSUE THREAD

**Issue by mapulse** [NicolasPetton/zerodark-theme#63]
icon set broken! [image](https://pasteboard.co/I40dtJ3.png) how to fix?

**Comment by NicolasPetton** [comment]
You have to install https://github.com/domtronn/all-the-icons.el first.

**Comment by mapulse** [comment]
I installed it and add require command but nothing change.

**Comment by NicolasPetton** [comment]
Ok, then I think you should report the issue to the `all-the-icons` project, Zerodark is only using the provided icons.

**Comment by lynxcode** [comment]
Thanks, I download all the icons font folder and copy all the directory and solved

**Comment by mapulse** [comment]
I solved my problem. I download font files and copy them to all-the-icons directory. thanks
