### ISSUE TITLE
Bump patch version to include last fixes

### ISSUE THREAD

**Issue by fishinthecalculator** [NicolasPetton/zerodark-theme#64]
Hello I'm in the process of packaging zerodark for [Guix](https://guix.gnu.org/). Well actually I already did, but I'm waiting to submit it because I was wondering if you could help.

Being Guix all about reproducible builds, it uses the package repository tags to checkout and build a given version of the package. I noticed that the last tagged release is 4.5 from about two years ago, but in the meantime a lot of fixes and pull requests were merged.

Could you bump the patch version of zerodark ( 4.5.1 for example) and release a tagged version to allow me to include all the last fixes in the Guix package?

**Comment by NicolasPetton** [comment]
fishinthecalculator <notifications@github.com> writes:

> Could you bump the patch version of zerodark ( 4.5.1 for example) and
> release a tagged version to allow me to include all the last fixes in
> the Guix package?

I just pushed a new tag!
Cheers!
