### ISSUE TITLE
Coloured rectangles in magit-status

### ISSUE THREAD

**Issue by manuel-uberti** [NicolasPetton/zerodark-theme#9]
This is a question based upon personal taste rather than an actual issue with your theme.

Are these rectangles really necessary?
![magit](https://cloud.githubusercontent.com/assets/8199224/18032819/04469544-6d13-11e6-9329-96e607945e0e.png)

Colours already make the distinction visible. Again, this is just personal taste.
![magit](https://cloud.githubusercontent.com/assets/8199224/18033025/c753affa-6d17-11e6-8c9d-9202cfea0f33.png)

**Comment by NicolasPetton** [comment]
It's not necessary, but shows branches as tags (or something similar),
which I like.

**Comment by manuel-uberti** [comment]
Thanks for the clarification. 

(Still rocking your theme both at home and in the office, by the way)

**Comment by NicolasPetton** [comment]
Manuel Uberti notifications@github.com writes:

> (Still rocking your theme both at home and in the office, by the way)

Awesome! If you have other suggestions, just tell me.
